### ISSUE TITLE
Need accordion text element to start with all sections closed

### ISSUE THREAD

**Issue by MichaelDLloyd** [Rodrigo-Ludgero/rlaccordion#1]
Excellent accordion text element!

I need an accordion element that initially starts with all sections closed. If you would be kind enough to modify your accordion widget to operate this way I would love to include it in my project.

Thank you for your time and consideration.

**Comment by rludgero** [comment]
Hi @MichaelDLloyd,

I updated the plugin, and add childNumOptions to permit display the childNum accordion option.

```
    childNumOptions: true,      // Active childNum option
    childNum: 0,                // number of the children start open
```

### Start all closed

```
    $("#second").rlAccordion('single', {
        childNumOptions: false
    });
```

Now, you can add the option to start with all sections closed.

Cheers!

**Comment by MichaelDLloyd** [comment]
Rodrigo,

You're awesome! Thank you very much for that refinement..

If you make web sites, check out a tool I found...
WYSIWYG Web Builder http://www.wysiwygwebbuilder.com
You can change the ribbon menu to regular pull down style
The program has more than 300 'extensions' to extend capability
Responsive
Very powerful application, don't let the $50 price fool you!

Thanks again for the refinement.

_Michael_
