### ISSUE TITLE
Code correction

### ISSUE THREAD

**Issue by MichaelDLloyd** [Rodrigo-Ludgero/rlaccordion#2]
Thank you again for modifying the accordion text. The functionality is excellent.
The following are code corrections that should be implemented:

  In 'js' folder, the file 'scripts.js' contains the following code:
$("#thirth").rlAccordion('mix', {
        childNum: 4
    });

  Code should be changed to the following:
$("#third").rlAccordion('mix', {
        childNumOptions: 4
    });

"#thirth" should be spelled "#third", with dependent reference changed in rlaccordion.html.
"childNum:" must be changed to "childNumOptions:" to function correctly.

**Comment by rludgero** [comment]
Hi @MichaelDLloyd ,

> Code should be changed to the following:
> $("#third").rlAccordion('mix', {
>         childNumOptions: 4
> });

the **childNumOptions** is a boolean, only accepts **true** or **false** **0** or **1**.

This options **childNumOptions** have a default value **true**  `childNumOptions: true` // Active childNum option.

For assign a number of the children, with do you want start open, you have to declare a **childNum** option, like that `childNum: 2`.

> "#thirth" should be spelled "#third", with dependent reference changed in rlaccordion.html.

The code inside of the scripts.js is only a sample, for add examples.

You can use what you want, is a class or id, for example:

```
$("#third").rlAccordion('mix', {
        childNum: 4
});
```

```
$(".third").rlAccordion('mix', {
        childNum: 2
});
```

```
$(".whatever").rlAccordion('single', {
        childNum: 5
});
```

```
$("#my-custom-accordeon").rlAccordion('single', {
        childNum: 1
});
```

Cheers!
